require('base')
require('keymap')
require('neovide')

require('plugins/packerconf')
require('plugins/nvimtreeconf')
require('plugins/colorizerconf')
require('plugins/indentconf')
require('plugins/rainbowconf')
require('plugins/vgitconf')
require('plugins/cocconf')
require('plugins/autopairsconf')
require('plugins/tsconf')
